#!/usr/bin/env python3
"""
gen_config.py — Generate an ORB-SLAM3 RGB-D configuration YAML from ZED camera intrinsics.

Usage:
    # From a running zed_pub_node (reads live camera_info topic):
    python -m robot.nav.orbslam3.gen_config --out /tmp/orb_zed.yaml

    # With hardcoded defaults (no ZED required):
    python -m robot.nav.orbslam3.gen_config --out /tmp/orb_zed.yaml --no-zed

The generated YAML is consumed by ORB-SLAM3's RGB-D example:
    ./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt /tmp/orb_zed.yaml ...
"""

import argparse
import sys
import time
from pathlib import Path

# ── Default ZED VGA intrinsics (fallback when ZED is offline) ─────────────────
# These match the ZED SDK default for VGA @ 30fps (used in zed_pub_node.py main()).
_DEFAULT_INTRINSICS = {
    "fx": 350.457,
    "fy": 350.457,
    "cx": 337.395,
    "cy": 189.396,
    "width": 672,
    "height": 376,
    # ZED left-right baseline (m) — fixed hardware spec
    "baseline": 0.12,
}

# ── ORB-SLAM3 tuning for indoor mobile robots ─────────────────────────────────
# These are conservative values suitable for hallway / office navigation.
# The RGB-D depth cutoff (DepthMapFactor * ThDepth) determines stereo/mono
# boundary; we set a generous 8m to match zed_pub_node's depth_max_range_m.
_ORB_PARAMS = {
    # ORB feature extraction
    "nFeatures": 1000,           # keypoints per frame — increase for large rooms
    "scaleFactor": 1.2,          # image pyramid scale
    "nLevels": 8,                # pyramid levels
    "iniThFAST": 20,             # initial FAST threshold
    "minThFAST": 7,              # minimum FAST threshold

    # Depth
    "DepthMapFactor": 1.0,       # depth scale (ZED outputs metres already → 1.0)
    "ThDepth": 40.0,             # baseline*ThDepth = far-depth threshold in meters
                                 # 0.12 m baseline × 40 = 4.8 m; beyond = mono mode

    # Viewer (disabled when running headless via orbslam_bridge)
    "Viewer.on": 0,
}

_YAML_TEMPLATE = """%YAML:1.0

# ──────────────────────────────────────────────────────────────────────────────
# ORB-SLAM3 RGB-D configuration — auto-generated for ZED camera
# Generated by robot/nav/orbslam3/gen_config.py
# ──────────────────────────────────────────────────────────────────────────────

Camera.type: "PinHole"

# Camera intrinsics (pixels)
Camera.fx: {fx:.6f}
Camera.fy: {fy:.6f}
Camera.cx: {cx:.6f}
Camera.cy: {cy:.6f}

# Distortion coefficients (ZED rectified images are undistorted → all zeros)
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

# Image resolution
Camera.width: {width:d}
Camera.height: {height:d}

# Camera frames per second
Camera.fps: 30.0

# RGB or BGR (ZED publishes RGB)
Camera.RGB: 1

# Stereo baseline (metres) × focal-length for depth scale
# Used internally by ORB-SLAM3 to compute ThDepth in pixels
Camera.bf: {bf:.6f}

# Close/far threshold: baseline × ThDepth (metres)
ThDepth: {ThDepth:.1f}

# Depth map scale factor: 1.0 because ZED depth is in metres
DepthMapFactor: {DepthMapFactor:.1f}

# ──────────────────────────────────────────────────────────────────────────────
# ORB Extractor
# ──────────────────────────────────────────────────────────────────────────────
ORBextractor.nFeatures: {nFeatures:d}
ORBextractor.scaleFactor: {scaleFactor:.2f}
ORBextractor.nLevels: {nLevels:d}
ORBextractor.iniThFAST: {iniThFAST:d}
ORBextractor.minThFAST: {minThFAST:d}

# ──────────────────────────────────────────────────────────────────────────────
# Viewer (set to 0 for headless operation)
# ──────────────────────────────────────────────────────────────────────────────
Viewer.on: {Viewer_on:d}
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
"""


def fetch_intrinsics_from_zed(
    zed_host: str = "127.0.0.1",
    zed_port: int = 6000,
    timeout_s: float = 8.0,
) -> dict:
    """Subscribe to zed/camera_info and return the intrinsics dict.

    Returns None if the topic is not available within timeout_s.

    Uses commlink 0.4.0 pull mode (buffer=False): sub[topic] returns the
    latest published value; no socket timeout configuration needed.
    """
    try:
        from commlink import Subscriber

        # Pull mode: each sub[topic] call polls the publisher for the latest
        # cached value. First call blocks until data arrives or we time out.
        sub = Subscriber(host=zed_host, port=zed_port, topics=["zed/camera_info"])

        t0 = time.time()
        info = None
        while (time.time() - t0) < timeout_s:
            try:
                info = sub["zed/camera_info"]
                if info is not None:
                    break
            except Exception:
                pass
            time.sleep(0.1)

        sub.stop()
        return info
    except Exception as exc:
        print(f"[gen_config] Could not fetch camera info from ZED: {exc}", file=sys.stderr)
        return None



def build_yaml(intrinsics: dict) -> str:
    """Render the YAML string from an intrinsics dict."""
    fx = float(intrinsics.get("fx", _DEFAULT_INTRINSICS["fx"]))
    fy = float(intrinsics.get("fy", _DEFAULT_INTRINSICS["fy"]))
    cx = float(intrinsics.get("cx", _DEFAULT_INTRINSICS["cx"]))
    cy = float(intrinsics.get("cy", _DEFAULT_INTRINSICS["cy"]))
    W  = int(intrinsics.get("width",  _DEFAULT_INTRINSICS["width"]))
    H  = int(intrinsics.get("height", _DEFAULT_INTRINSICS["height"]))
    B  = float(intrinsics.get("baseline", _DEFAULT_INTRINSICS["baseline"]))

    # Camera.bf = baseline [m] × fx [px]  (ORB-SLAM3 convention)
    bf = B * fx

    return _YAML_TEMPLATE.format(
        fx=fx, fy=fy, cx=cx, cy=cy,
        width=W, height=H,
        bf=bf,
        ThDepth=_ORB_PARAMS["ThDepth"],
        DepthMapFactor=_ORB_PARAMS["DepthMapFactor"],
        nFeatures=_ORB_PARAMS["nFeatures"],
        scaleFactor=_ORB_PARAMS["scaleFactor"],
        nLevels=_ORB_PARAMS["nLevels"],
        iniThFAST=_ORB_PARAMS["iniThFAST"],
        minThFAST=_ORB_PARAMS["minThFAST"],
        Viewer_on=_ORB_PARAMS["Viewer.on"],
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate an ORB-SLAM3 YAML config from ZED camera intrinsics."
    )
    parser.add_argument(
        "--out", default="/tmp/orb_zed.yaml",
        help="Output YAML path (default: /tmp/orb_zed.yaml)",
    )
    parser.add_argument(
        "--no-zed", action="store_true",
        help="Skip ZED subscriber; use hardcoded VGA defaults.",
    )
    parser.add_argument(
        "--zed-host", default="127.0.0.1",
        help="Host running zed_pub_node (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--zed-port", type=int, default=6000,
        help="ZMQ port for zed_pub_node (default: 6000)",
    )
    parser.add_argument(
        "--features", type=int, default=_ORB_PARAMS["nFeatures"],
        help="Number of ORB features per frame (default: 1000).",
    )
    parser.add_argument(
        "--viewer", action="store_true",
        help="Enable the Pangolin viewer in ORB-SLAM3 (disable for headless).",
    )
    args = parser.parse_args()

    _ORB_PARAMS["nFeatures"] = args.features
    _ORB_PARAMS["Viewer.on"] = 1 if args.viewer else 0

    intrinsics = _DEFAULT_INTRINSICS.copy()
    if not args.no_zed:
        print(f"[gen_config] Fetching camera intrinsics from {args.zed_host}:{args.zed_port} …")
        live = fetch_intrinsics_from_zed(args.zed_host, args.zed_port)
        if live:
            intrinsics.update(live)
            print(f"[gen_config] Got live intrinsics: fx={intrinsics['fx']:.2f} "
                  f"fy={intrinsics['fy']:.2f} "
                  f"cx={intrinsics['cx']:.2f} cy={intrinsics['cy']:.2f} "
                  f"W={intrinsics['width']} H={intrinsics['height']}")
        else:
            print("[gen_config] WARN: No live intrinsics — using VGA defaults.", file=sys.stderr)
    else:
        print("[gen_config] Using hardcoded VGA defaults (--no-zed).")

    yaml_str = build_yaml(intrinsics)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_str)
    print(f"[gen_config] Wrote ORB-SLAM3 config → {out_path}")


if __name__ == "__main__":
    main()
