#!/usr/bin/env python3
"""
config.py — Generate an ORB-SLAM3 RGB-D configuration YAML from ZED camera intrinsics.

Self-contained config generator for orbv2.  Can auto-fetch live intrinsics
from the running zed_pub_node or fall back to hardcoded ZED VGA defaults.

Usage:
    # From a running zed_pub_node (reads live camera_info topic):
    python -m orbv2.config --out /tmp/orb_zed.yaml

    # With hardcoded defaults (no ZED required):
    python -m orbv2.config --out /tmp/orb_zed.yaml --no-zed
"""

import argparse
import sys
import time
from pathlib import Path

# ── Default ZED VGA intrinsics (fallback when ZED is offline) ─────────────────
# Match the ZED SDK default for VGA @ 30fps (used in zed_pub_node.py main()).
DEFAULT_INTRINSICS = {
    "fx": 350.457,
    "fy": 350.457,
    "cx": 337.395,
    "cy": 189.396,
    "width": 672,
    "height": 376,
    # ZED 2i left-right baseline (m) — fixed hardware spec
    "baseline": 0.12,
}

# ── ORB-SLAM3 tuning for indoor mobile robots ─────────────────────────────────
ORB_PARAMS = {
    # ORB feature extraction
    "nFeatures": 1000,       # keypoints per frame — increase for large rooms
    "scaleFactor": 1.2,      # image pyramid scale
    "nLevels": 8,            # pyramid levels
    "iniThFAST": 20,         # initial FAST threshold
    "minThFAST": 7,          # minimum FAST threshold

    # Depth
    "DepthMapFactor": 1.0,   # depth scale (ZED outputs metres → 1.0)
    "ThDepth": 40.0,         # baseline×ThDepth = far-depth threshold in meters
                             # 0.12 m baseline × 40 = 4.8 m; beyond = mono mode

    # Viewer (disabled when running headless via orbv2 bridge)
    "Viewer.on": 0,
}

_YAML_TEMPLATE = """%YAML:1.0

# ──────────────────────────────────────────────────────────────────────────────
# ORB-SLAM3 RGB-D configuration — auto-generated for ZED 2i camera
# Generated by orbv2/config.py
# ──────────────────────────────────────────────────────────────────────────────

Camera.type: "PinHole"

# Camera intrinsics (pixels)
Camera.fx: {fx:.6f}
Camera.fy: {fy:.6f}
Camera.cx: {cx:.6f}
Camera.cy: {cy:.6f}

# Distortion coefficients (ZED rectified images are undistorted → all zeros)
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

# Image resolution
Camera.width: {width:d}
Camera.height: {height:d}

# Camera frames per second
Camera.fps: 30.0

# RGB or BGR (ZED publishes RGB)
Camera.RGB: 1

# Stereo baseline (metres) × focal-length for depth scale
Camera.bf: {bf:.6f}

# Close/far threshold: baseline × ThDepth (metres)
ThDepth: {ThDepth:.1f}

# Depth map scale factor: 1.0 because ZED depth is in metres
DepthMapFactor: {DepthMapFactor:.1f}

# ──────────────────────────────────────────────────────────────────────────────
# ORB Extractor
# ──────────────────────────────────────────────────────────────────────────────
ORBextractor.nFeatures: {nFeatures:d}
ORBextractor.scaleFactor: {scaleFactor:.2f}
ORBextractor.nLevels: {nLevels:d}
ORBextractor.iniThFAST: {iniThFAST:d}
ORBextractor.minThFAST: {minThFAST:d}

# ──────────────────────────────────────────────────────────────────────────────
# Viewer (set to 0 for headless operation)
# ──────────────────────────────────────────────────────────────────────────────
Viewer.on: {Viewer_on:d}
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
"""


def fetch_intrinsics_from_zed(
    zed_host: str = "127.0.0.1",
    zed_port: int = 6000,
    timeout_s: float = 8.0,
) -> dict:
    """Subscribe to zed/camera_info and return the intrinsics dict.

    Returns None if the topic is not available within timeout_s.
    """
    try:
        from commlink import Subscriber

        sub = Subscriber(
            host=zed_host, port=zed_port, topics=["zed/camera_info"]
        )

        t0 = time.time()
        info = None
        while (time.time() - t0) < timeout_s:
            try:
                info = sub["zed/camera_info"]
                if info is not None:
                    break
            except Exception:
                pass
            time.sleep(0.1)

        sub.stop()
        return info
    except Exception as exc:
        print(
            f"[orbv2.config] Could not fetch camera info from ZED: {exc}",
            file=sys.stderr,
        )
        return None


def build_yaml(intrinsics: dict, orb_params: dict = None) -> str:
    """Render the ORB-SLAM3 YAML string from an intrinsics dict."""
    if orb_params is None:
        orb_params = ORB_PARAMS

    fx = float(intrinsics.get("fx", DEFAULT_INTRINSICS["fx"]))
    fy = float(intrinsics.get("fy", DEFAULT_INTRINSICS["fy"]))
    cx = float(intrinsics.get("cx", DEFAULT_INTRINSICS["cx"]))
    cy = float(intrinsics.get("cy", DEFAULT_INTRINSICS["cy"]))
    W  = int(intrinsics.get("width",  DEFAULT_INTRINSICS["width"]))
    H  = int(intrinsics.get("height", DEFAULT_INTRINSICS["height"]))
    B  = float(intrinsics.get("baseline", DEFAULT_INTRINSICS["baseline"]))

    # Camera.bf = baseline [m] × fx [px]  (ORB-SLAM3 convention)
    bf = B * fx

    return _YAML_TEMPLATE.format(
        fx=fx, fy=fy, cx=cx, cy=cy,
        width=W, height=H,
        bf=bf,
        ThDepth=orb_params["ThDepth"],
        DepthMapFactor=orb_params["DepthMapFactor"],
        nFeatures=orb_params["nFeatures"],
        scaleFactor=orb_params["scaleFactor"],
        nLevels=orb_params["nLevels"],
        iniThFAST=orb_params["iniThFAST"],
        minThFAST=orb_params["minThFAST"],
        Viewer_on=orb_params["Viewer.on"],
    )


def generate_config(
    output_path: str = "/tmp/orb_zed.yaml",
    zed_host: str = "127.0.0.1",
    zed_port: int = 6000,
    use_zed: bool = True,
    n_features: int = None,
    viewer: bool = False,
) -> str:
    """Generate the ORB-SLAM3 config YAML and write to output_path.

    Returns the output path.
    """
    params = ORB_PARAMS.copy()
    if n_features is not None:
        params["nFeatures"] = n_features
    params["Viewer.on"] = 1 if viewer else 0

    intrinsics = DEFAULT_INTRINSICS.copy()
    if use_zed:
        print(
            f"[orbv2.config] Fetching camera intrinsics from "
            f"{zed_host}:{zed_port} …"
        )
        live = fetch_intrinsics_from_zed(zed_host, zed_port)
        if live:
            intrinsics.update(live)
            print(
                f"[orbv2.config] Got live intrinsics: "
                f"fx={intrinsics['fx']:.2f} fy={intrinsics['fy']:.2f} "
                f"cx={intrinsics['cx']:.2f} cy={intrinsics['cy']:.2f} "
                f"W={intrinsics['width']} H={intrinsics['height']}"
            )
        else:
            print(
                "[orbv2.config] WARN: No live intrinsics — using VGA defaults.",
                file=sys.stderr,
            )
    else:
        print("[orbv2.config] Using hardcoded VGA defaults (--no-zed).")

    yaml_str = build_yaml(intrinsics, params)

    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_str)
    print(f"[orbv2.config] Wrote ORB-SLAM3 config → {out_path}")
    return str(out_path)


def main():
    parser = argparse.ArgumentParser(
        description="Generate an ORB-SLAM3 YAML config from ZED camera intrinsics."
    )
    parser.add_argument(
        "--out", default="/tmp/orb_zed.yaml",
        help="Output YAML path (default: /tmp/orb_zed.yaml)",
    )
    parser.add_argument(
        "--no-zed", action="store_true",
        help="Skip ZED subscriber; use hardcoded VGA defaults.",
    )
    parser.add_argument(
        "--zed-host", default="127.0.0.1",
        help="Host running zed_pub_node (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--zed-port", type=int, default=6000,
        help="ZMQ port for zed_pub_node (default: 6000)",
    )
    parser.add_argument(
        "--features", type=int, default=None,
        help="Number of ORB features per frame (default: 1000).",
    )
    parser.add_argument(
        "--viewer", action="store_true",
        help="Enable the Pangolin viewer in ORB-SLAM3 (disable for headless).",
    )
    args = parser.parse_args()

    generate_config(
        output_path=args.out,
        zed_host=args.zed_host,
        zed_port=args.zed_port,
        use_zed=not args.no_zed,
        n_features=args.features,
        viewer=args.viewer,
    )


if __name__ == "__main__":
    main()
